site_name: csnotes
theme: 
  name: 'material'
  language: 'zh'
  icon:
    logo: material/library
    repo: fontawesome/brands/github
  favicon: img/green_aleph.jpg
  features:
    - navigation.top
    - navigation.tabs
    - navigation.instant
  palette:
    - primary: teal
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

repo_name: 'lzy-tony/csnotes'
repo_url: 'https://github.com/lzy-tony/csnotes/'

extra:
  pagetime: 'on'

nav:
  - 计算机科学:
    - 密码学:
      - 现代密码学:
        - 说明: cs/cryptography/cryptography/info.md
        - 绪论: cs/cryptography/cryptography/intro.md
        - 数学前置: cs/cryptography/cryptography/math.md
        - 古典密码学: cs/cryptography/cryptography/classic.md
        - Shannon 理论: cs/cryptography/cryptography/shannon.md
        - 分组密码: cs/cryptography/cryptography/block_cipher.md
        - Hash 函数: cs/cryptography/cryptography/hash.md
        - 公钥密码体系: cs/cryptography/cryptography/public_key.md
        - 数字签名: cs/cryptography/cryptography/signature.md
  - 论文:
    - AI:
      - 对抗攻防:
        - PGD: papers/ai/adversarial_attack/pgd.md
        - PS-GAN: papers/ai/adversarial_attack/ps-gan.md
      - 目标识别:
        - R-CNN: papers/ai/object_detection/r-cnn.md
        - YOLOv1: papers/ai/object_detection/yolov1.md
        - YOLOv2: papers/ai/object_detection/yolov2.md
        - YOLOv3: papers/ai/object_detection/yolov3.md

extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/mathjax@2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      locale: zh

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - def_list
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

